name             'mule'
maintainer       'ShopKeep DevOps'
maintainer_email 'devops@shopkeep.com'
license          'All rights reserved'
description      'Installs/Configures mule'
long_description 'Installs/Configures mule'
version          '0.1.4'

depends 'archive'
depends 'java'
